os: Unstable

environment:
  GITHUB_TOKEN:
    secure: XHO7MYVx17hrAWLVGs1eGJZcIRczb4ddHrFZj/Be3mVO54ITNLpXR5uquH/9MqAl
  PSGALLERY_TOKEN:
    secure: yljpqxZjLKG2ZxEbEN6u07UxOyDOGiAbIhA64CN9BVCoRPSzZTykdtQ9r/kAztJG
    
configuration:
  - Debug
  - Release    

install:
  - ps: $env:PATH=("C:\Program Files (x86)\MSBuild\14.0\Bin;"+$env:PATH)
  - ps: mkdir c:/Modules
  - ps: $env:PSModulePath += ";c:\Modules\"
  - ps: cinst pester -y
    
before_build:
  - ps: pushd GithubProvider
  - ps: nuget restore
  - ps: popd    
    
test_script:
  - ps: .\test.ps1
    
deploy_script:
  - ps: cp GithubFS c:/Modules/GithubFS
  - ps: publish-module -Name GithubFS -NugetApiToken $env:PSGALLERY_TOKEN
    on:
      branch: master
      appveyor_repo_tag: true 
