os: WMF 5

environment:
  GITHUB_TOKEN:
    secure: XHO7MYVx17hrAWLVGs1eGJZcIRczb4ddHrFZj/Be3mVO54ITNLpXR5uquH/9MqAl
  PSGALLERY_TOKEN:
    secure: yljpqxZjLKG2ZxEbEN6u07UxOyDOGiAbIhA64CN9BVCoRPSzZTykdtQ9r/kAztJG
    
configuration:
  - Debug
  - Release    

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "1.0.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

install:
  - ps: $env:PATH=("C:\Program Files (x86)\MSBuild\14.0\Bin;"+$env:PATH)
  - ps: mkdir c:/Modules
  - ps: $env:PSModulePath += ";c:\Modules\"
  - ps: cinst pester -y
  - ps: Get-PackageProvider -Name NuGet -Force
    
before_build:
  - ps: pushd GithubProvider
  - ps: nuget restore
  - ps: popd    
    
test_script:
  - ps: .\test.ps1
    
deploy_script:
  - ps: "if ($env:APPVEYOR_REPO_TAG -eq 'true') { cp GithubFS c:/Modules/GithubFS; publish-module -Name GithubFS -NuGetApiKey $env:PSGALLERY_TOKEN }"
