os: Visual Studio 2015 RC

environment:
  GITHUB_TOKEN:
    secure: PTJuUJLTdJTgSCatNWHnVejoZdTkrYBMLBe6UM46LXMy/sxk+KCLD9J6URu5q0JG
  PSGALLERY_TOKEN:
    secure: yljpqxZjLKG2ZxEbEN6u07UxOyDOGiAbIhA64CN9BVCoRPSzZTykdtQ9r/kAztJG

install:
  - ps: $env:PATH=("C:\Program Files (x86)\MSBuild\14.0\Bin;"+$env:PATH)
  - ps: mkdir c:/Modules
  - ps: $env:PSModulePath += ";c:\Modules\"
  - ps: (new-object Net.WebClient).DownloadString("http://psget.net/GetPsGet.ps1") | iex
  - ps: install-module pester
    
before_build:
  - ps: pushd GithubProvider
  - ps: nuget restore
  - ps: popd    
    
test_script:
  - ps: .\test.ps1
    
deploy_script:
  - ps: cp GithubFS c:/Modules/GithubFS
  - ps: publish-module -Name GithubFS -NugetApiToken $env:PSGALLERY_TOKEN
    on:
      branch: master
      appveyor_repo_tag: true 
